language: php

php:
    - 7.1

env:
    - DOCTRINE_VERSION="2.3.*"
    - DOCTRINE_VERSION="2.4.*"
    - DOCTRINE_VERSION="2.5.*"

matrix:
    include:
        - php: 7.1
          env: DOCTRINE_VERSION="dev-master"

before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar require doctrine/orm:${DOCTRINE_VERSION} doctrine/dbal:${DOCTRINE_VERSION} --dev --no-interaction --prefer-source
    - cp phpunit.xml.dist phpunit.xml
